server:
    port: 8080

spring:
    datasource:
        url: jdbc:mysql://mini-survey-monkey-sql-server.mysql.database.azure.com:3306/mydb
        username: myadmin
        password: sysc4806!
    jpa:
        hibernate:
            ddl-auto: create-drop
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect
                format_sql: true
        show-sql: true
    main:
        web-application-type: servlet